### ISSUE TITLE
"export 'ColladaLoader' or 'OrbitControls' (imported as 'THREE') was not found in 'three'

### ISSUE THREAD

**Issue by Huang9495** [makimenko/akibot-ui#1]
I execute the command from the offical website (https://github.com/makimenko/akibot-ui/) and no issue take place.But after I type to the code of ng serve .The issues is here:

The issue is here:
 One: "export 'ColladaLoader' (imported as 'THREE') was not found in 'three'"
 Two: "export 'OrbitControls' (imported as 'THREE') was not found in 'three'"

I find the three/examples/js/loaders/ColladaLoader.But I don't know where the Three is start-up the .And how to do ?
![screenshot from 2017-09-16 17 55 20](https://user-images.githubusercontent.com/26674689/30511291-3f83f754-9b08-11e7-94d1-21c7b18523c0.png)

**Comment by makimenko** [comment]
Dear Huang949,
Just ignore this warning. The problem is that OrbitControls and ColladaLoader is not part of THREE module yet. See some info here:
https://github.com/mrdoob/three.js/issues/9562
